// Static data for the website (no database needed)

export const services = [
  {
    id: "1",
    slug: "bbbee-strategy",
    title: "B-BBEE Strategy & Roadmap",
    summary: "Build a practical transformation roadmap aligned to your business goals and compliance requirements.",
    body: "Our B-BBEE strategy service helps you develop a comprehensive transformation plan that integrates seamlessly with your business objectives. We work with you to understand your current state, identify opportunities, and create a roadmap that drives both compliance and business value.",
    outcome: "A clear, actionable B-BBEE strategy that aligns with your business goals and sets you on a path to sustainable transformation.",
    whoItsFor: "Organisations looking to:\n• Develop their first B-BBEE strategy\n• Refresh or update existing strategies\n• Align transformation with business objectives\n• Prepare for verification",
    deliverables: "B-BBEE Strategy Document\nCurrent State Assessment\nTransformation Roadmap\nImplementation Plan\nScorecard Projections",
    imageUrl: null,
    order: 0,
    seoTitle: "B-BBEE Strategy & Roadmap | REAP Solutions",
    seoDescription: "Comprehensive B-BBEE strategy development and transformation roadmap services.",
    published: true,
  },
  {
    id: "2",
    slug: "ownership-advisory",
    title: "Ownership Advisory & Structuring",
    summary: "Get specialist guidance on ownership structures, partner profiles, and funding models that make commercial sense.",
    body: "Ownership transformation is a critical element of B-BBEE. We provide expert advisory on structuring ownership deals that work for all parties. Our approach focuses on creating sustainable, commercially viable ownership arrangements that deliver real value.",
    outcome: "A well-structured ownership arrangement that meets B-BBEE requirements while creating value for all stakeholders.",
    whoItsFor: "Companies seeking to:\n• Structure ownership transactions\n• Identify and evaluate potential partners\n• Understand funding options\n• Navigate ownership compliance",
    deliverables: "Ownership Structure Analysis\nPartner Profile Development\nTransaction Advisory\nCompliance Assessment\nImplementation Support",
    imageUrl: null,
    order: 1,
    seoTitle: "Ownership Advisory & Structuring | REAP Solutions",
    seoDescription: "Expert ownership transformation advisory and structuring services.",
    published: true,
  },
  {
    id: "3",
    slug: "enterprise-supplier-development",
    title: "Enterprise & Supplier Development",
    summary: "Design ESD initiatives that strengthen supplier pipelines and improve scorecard outcomes sustainably.",
    body: "Enterprise and Supplier Development (ESD) is essential for both B-BBEE compliance and building resilient supply chains. We help you design and implement ESD programmes that create real value for your business and your suppliers.",
    outcome: "A sustainable ESD programme that improves your B-BBEE scorecard while building stronger supplier relationships.",
    whoItsFor: "Organisations that:\n• Need to improve ESD scorecard points\n• Want to develop their supplier base\n• Seek to build sustainable supplier relationships\n• Require ESD programme design and implementation",
    deliverables: "ESD Programme Design\nSupplier Identification & Selection\nProgramme Implementation Plan\nMonitoring & Evaluation Framework\nImpact Assessment",
    imageUrl: null,
    order: 2,
    seoTitle: "Enterprise & Supplier Development | REAP Solutions",
    seoDescription: "Enterprise and Supplier Development programme design and implementation.",
    published: true,
  },
  {
    id: "4",
    slug: "skills-planning",
    title: "Skills Development Planning",
    summary: "Strategic skills development planning that aligns with B-BBEE requirements and business needs.",
    body: "Skills development is a key element of B-BBEE transformation. We help you develop strategic skills development plans that meet compliance requirements while addressing your actual business needs and building internal capability.",
    outcome: "A strategic skills development plan that improves your B-BBEE scorecard and builds internal capability.",
    whoItsFor: "Companies needing to:\n• Develop skills development strategies\n• Maximise skills development points\n• Align training with business needs\n• Plan and execute skills programmes",
    deliverables: "Skills Development Strategy\nTraining Needs Analysis\nProgramme Design\nImplementation Plan\nMonitoring Framework",
    imageUrl: null,
    order: 3,
    seoTitle: "Skills Development Planning | REAP Solutions",
    seoDescription: "Strategic skills development planning for B-BBEE compliance.",
    published: true,
  },
  {
    id: "5",
    slug: "training-and-coaching",
    title: "Training & Coaching Programs",
    summary: "Practical workshops and coaching to help teams understand the Codes and implement transformation correctly.",
    body: "Our training and coaching programmes equip your team with the knowledge and skills needed to implement B-BBEE transformation effectively. We offer both public workshops and customised in-house training.",
    outcome: "A team that understands B-BBEE requirements and has the skills to implement transformation effectively.",
    whoItsFor: "Teams that need:\n• B-BBEE fundamentals training\n• Implementation coaching\n• Scorecard understanding\n• Transformation best practices",
    deliverables: "Customised Training Programmes\nWorkshop Materials\nCoaching Sessions\nImplementation Support\nKnowledge Transfer",
    imageUrl: null,
    order: 4,
    seoTitle: "Training & Coaching Programs | REAP Solutions",
    seoDescription: "B-BBEE training and coaching programmes for teams.",
    published: true,
  },
  {
    id: "6",
    slug: "transaction-advisory",
    title: "Transaction Advisory",
    summary: "Expert advisory for B-BBEE transactions, mergers, and acquisitions.",
    body: "B-BBEE transactions require careful planning and execution. We provide advisory services for ownership transactions, mergers, acquisitions, and other transformation-related deals.",
    outcome: "Successfully executed B-BBEE transactions that meet compliance requirements and create value.",
    whoItsFor: "Companies involved in:\n• Ownership transactions\n• Mergers and acquisitions\n• B-BBEE deal structuring\n• Transaction compliance",
    deliverables: "Transaction Advisory\nDue Diligence Support\nDeal Structuring\nCompliance Assessment\nImplementation Support",
    imageUrl: null,
    order: 5,
    seoTitle: "Transaction Advisory | REAP Solutions",
    seoDescription: "B-BBEE transaction advisory and deal structuring services.",
    published: true,
  },
]

export const faqs = [
  {
    id: "1",
    question: "What is B-BBEE and why does it matter?",
    answer: "Broad-Based Black Economic Empowerment (B-BBEE) is a South African government policy framework aimed at promoting economic transformation and increasing the participation of black people in the economy. It matters because it can impact your ability to do business with government and large corporates, and it's a legal requirement for many companies operating in South Africa.",
    order: 0,
    published: true,
  },
  {
    id: "2",
    question: "How long does it take to develop a B-BBEE strategy?",
    answer: "The timeline depends on the complexity of your organisation and your specific needs. Typically, a comprehensive B-BBEE strategy can be developed in 4-8 weeks, including assessment, planning, and documentation. We'll provide a detailed timeline during our initial consultation.",
    order: 1,
    published: true,
  },
  {
    id: "3",
    question: "Do you work with small businesses?",
    answer: "Yes, we work with businesses of all sizes, from small enterprises to large corporates. Our approach is tailored to your specific context, resources, and objectives. We understand that small businesses have different needs and constraints, and we design solutions accordingly.",
    order: 2,
    published: true,
  },
  {
    id: "4",
    question: "What is the difference between B-BBEE and BBBEE?",
    answer: "B-BBEE (Broad-Based Black Economic Empowerment) and BBBEE refer to the same thing. B-BBEE is the official acronym used in legislation, while BBBEE is a common alternative spelling. Both terms refer to the same transformation framework in South Africa.",
    order: 3,
    published: true,
  },
  {
    id: "5",
    question: "How do you measure the success of a B-BBEE programme?",
    answer: "Success is measured through multiple indicators: improved B-BBEE scorecard ratings, achievement of transformation targets, business growth, stakeholder value creation, and sustainable implementation. We work with you to define success metrics that align with both compliance requirements and business objectives.",
    order: 4,
    published: true,
  },
]

export const clients = [
  {
    id: "1",
    name: "Thebe Investment Corporation",
    logoUrl: "/images/partners/Thebe_Investments_Dark-Skin-Logo.png",
    websiteUrl: null,
    industry: "Investment",
    order: 0,
    featured: true,
  },
  {
    id: "2",
    name: "Aberdare Cables",
    logoUrl: "/images/partners/0000692180_resized_aberdare.jpg",
    websiteUrl: null,
    industry: "Manufacturing",
    order: 1,
    featured: true,
  },
  {
    id: "3",
    name: "Nokia South Africa",
    logoUrl: "/images/partners/Nokia-South-Africa.jpg",
    websiteUrl: null,
    industry: "Technology",
    order: 2,
    featured: true,
  },
  {
    id: "4",
    name: "Naamsa",
    logoUrl: "/images/partners/naamsa-final-logo-600.jpg",
    websiteUrl: null,
    industry: "Automotive",
    order: 3,
    featured: true,
  },
]

export const trainingPrograms = [
  {
    id: "1",
    slug: "bbbee-fundamentals",
    title: "B-BBEE Fundamentals",
    summary: "Introduction to B-BBEE codes, scorecards, and transformation requirements.",
    body: "This foundational programme covers the basics of B-BBEE, including understanding the codes, scorecard elements, and key transformation requirements.",
    duration: "1 day",
    audience: "Business owners, managers, and transformation practitioners new to B-BBEE.",
    outcomes: ["Understand B-BBEE framework", "Read and interpret scorecards", "Identify transformation opportunities"],
    order: 0,
    published: true,
  },
  {
    id: "2",
    slug: "implementation-workshop",
    title: "B-BBEE Implementation Workshop",
    summary: "Practical workshop on implementing B-BBEE strategies and programmes.",
    body: "A hands-on workshop focused on practical implementation of B-BBEE strategies, including programme design, stakeholder engagement, and monitoring.",
    duration: "2 days",
    audience: "Transformation teams and practitioners responsible for B-BBEE implementation.",
    outcomes: ["Design implementation plans", "Engage stakeholders effectively", "Monitor and evaluate programmes"],
    order: 1,
    published: true,
  },
]

export const resources = [
  {
    id: "1",
    title: "B-BBEE Codes of Good Practice",
    slug: "bbbee-codes",
    summary: "Official B-BBEE Codes of Good Practice published by the Department of Trade, Industry and Competition.",
    url: "https://www.thedti.gov.za/economic_empowerment/bee_codes.jsp",
    tags: ["legislation", "codes", "official"],
    categoryId: null,
    featured: true,
    publishDate: new Date("2024-01-01"),
    sourceType: "link",
    readingTime: 30,
  },
]

export const resourceCategories = [
  {
    id: "1",
    name: "Legislation",
    slug: "legislation",
    description: "Official B-BBEE legislation and codes",
    order: 0,
  },
  {
    id: "2",
    name: "Guides",
    slug: "guides",
    description: "Practical guides and how-to resources",
    order: 1,
  },
  {
    id: "3",
    name: "Insights",
    slug: "insights",
    description: "Industry insights and analysis",
    order: 2,
  },
]


